name: Workflow lors d'un push
on: push

jobs:
    mon_premier_job:
        name: récupération install et message
        runs-on: ubuntu-latest
        steps:
            - name: récupération du code
              uses: actions/checkout@v4
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: maven
            - name: Build with Maven
              run: mvn -B package --file pom.xml
            - name: afficher un message pour indiquer le buid de l'appli
              run: echo "appli buildée"
            
            
            